project:
  type: website

website:
  title: "Noah Wotschke | Mechanical Engineering"
  navbar:
    background: "#1f407a"  # ETH Blue
    search: true
    left:
      - href: index.html
        text: Home
      - href: projects.html
        text: Projects
      - href: about/index.html
        text: About

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css